on:
  push:
    branches:
    - trunk

jobs:
  build:
    name: build for windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: 4.8.1
      
